Adapt to musl
Got:
cargo build --target=x86_64-unknown-linux-musl

error[E0063]: missing field `__pad1` in initializer of `libc::cmsghdr`
  --> /home/tim/project/virtcontainers/sendfd/src/lib.rs:92:13
   |
92 |             libc::cmsghdr {
   |             ^^^^^^^^^^^^^ missing `__pad1`

error[E0451]: field `__pad1` of struct `libc::msghdr` is private
  --> /home/tim/project/virtcontainers/sendfd/src/lib.rs:78:15
   |
78 |             ..mem::zeroed()
   |               ^^^^^^^^^^^^^ field `__pad1` is private

error[E0451]: field `__pad2` of struct `libc::msghdr` is private
  --> /home/tim/project/virtcontainers/sendfd/src/lib.rs:78:15
   |
78 |             ..mem::zeroed()
   |               ^^^^^^^^^^^^^ field `__pad2` is private

This commit will resolve the problem.

Signed-off-by: Tim Zhang <tim@hyper.sh>